### ISSUE TITLE
Specifically what do we want to teach

### ISSUE THREAD

**Issue by llmorreale** [HarvardForest/Rworkshop#18]
Thoughts on what to teach:
ddply for easy aggregation of data frames, or something else?
ggplot or base plot?

**Comment by MKLau** [comment]
Ggplot would be good.

Ddply, merge, duplicates, apply, and generally other data management would be good. 

I think that regardless less lecture is better though. This should be a way to get them to work through things on there own.

**Comment by MKLau** [comment]
I added code to do a scatterplot with ggplot.

**Comment by MKLau** [comment]
The ggplot code is currently in the class analysis script.
