### ISSUE TITLE
Look into Data Carptentry

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/Rworkshop#20]
http://www.datacarpentry.org/

**Comment by MKLau** [comment]
http://www.datacarpentry.org/lessons/#ecology-workshop

**Comment by MKLau** [comment]
I like their ecology structure with the exception of visualization as separate from analysis. My thought is that visualization is included in analysis, but the next step is communication/sharing/synthesis of results.

**Comment by llmorreale** [comment]
I agree, visualization should be integrated into the analysis steps. Perhaps we can distinguish in some way between how you would use visualization for analysis and ways you would make more complete figures for final results.
